### ISSUE TITLE
I only see tests that I've run in the Test Explorer

### ISSUE THREAD

**Issue by KellyBennett** [st0012/ruby-lsp-rspec#10]
First off. Thanks for this gem, it's working great!

I think I'd expect to see all my tests in the Text Explorer view, but instead I only see tests which have been run in the current VSCode session . How do I get all the tests to show up in that view?

**Comment by st0012** [comment]
Do you mean seeing all tests in the entire project instead of just the ones in the opened test files? 

If that's what you mean, it's out of this addon's control unfortunately. [`vscode-ruby-lsp`](https://github.com/Shopify/vscode-ruby-lsp) current generates Test Explorer entries with data from Code Lens, which is only sent when you open a test file.
